# Automated Vulnerability Scanning
# Runs Trivy scanner on all container images

apiVersion: batch/v1
kind: CronJob
metadata:
  name: vulnerability-scan
  namespace: petala-fashion
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trivy
            image: aquasec/trivy:latest
            command:
            - trivy
            - image
            - --severity
            - HIGH,CRITICAL
            - --exit-code
            - "1"
            - --format
            - json
            - --output
            - /reports/scan-results.json
            args:
            - directus/directus:10-latest
            - nginx:alpine
            - timescale/timescaledb:latest-pg17
            - redis:8-alpine
            - prom/prometheus:latest
            - grafana/grafana:latest
            volumeMounts:
            - name: scan-reports
              mountPath: /reports
          restartPolicy: OnFailure
          volumes:
          - name: scan-reports
            persistentVolumeClaim:
              claimName: scan-reports-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scan-reports-pvc
  namespace: petala-fashion
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3
